### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dannycolin** [alexmorley/meta-open-database#5]
So I was wondering **what are your opinion** on the license we should use for the source code and the content. 

Personally, I think we should try to be as much free and open as we can. IOW, we should go with a [copyleft license](https://en.wikipedia.org/wiki/Copyleft). 

For the source code, I'll suggest the AGPLv3 license since the project is an online service. The AGPLv3 ensure that "if you run a modified program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the modified version running there" ([source](https://www.gnu.org/licenses/why-affero-gpl.html)).

Even if I prefer the AGPLv3, I'll be also open to use the GPLv3 for the backend and the AGPLv3 only for the frontend so it will be more *permissive* to someone who want to host a modified version without distributing the modifications.

Now for the content, I'll go with a Creative Commons Attribution-ShareAlike. This license ensure that the data will stay open and that any modification to it even if it's on an instance external to ours can be merge back.

**Comment by alexmorley** [comment]
AGPLv3 and CC-By-SA sound like good places to start. We can always be more permissive later if it makes sense.

**Comment by alexmorley** [comment]
Can we just put two licenses in the root directory like LICENSE.code and LICENSE.content or is there a better way?

**Comment by dannycolin** [comment]
> Can we just put two licenses in the root directory like LICENSE.code and LICENSE.content or is there a better way?

Yes. ~~But having one LICENSE file listing the license for every components (with a link to the full text) would probably be more flexible~~.

I'll push a PR on my lunch break ;)
