### ISSUE TITLE
Deploy on a public server for demonstration / discussion

### ISSUE THREAD

**Issue by alexmorley** [alexmorley/meta-open-database#7]
As we're making decisions it'd be great it if there was a continuously deployed version from master that we can refer to. 

In doing this we can also set up some form on testing / single command deployment (e.g. via docker and/or Jenkins).

**Comment by alexmorley** [comment]
Progress http://www.meta-open-db.com

**Comment by dannycolin** [comment]
For anyone who join our project but don't know what Continuous Integration, Deployment & Delivery, [here's an article on OpenSource.com (and also other related concepts)](https://opensource.com/article/18/8/what-cicd).

**Comment by dannycolin** [comment]
@alexmorley what do you thing if we migrate the repository to GitLab. I can see two advantages to that:

- There's a continuous integration tool integrate in it (GitLab-CI).
- It's more Open than GitHub (with GitLab-CE). 

Oh and you can login with a GitHub or Google account and there's a migration tools that import the source code and all the issues so it shouldn't be to hard. We could, of course, keep a mirror on GitHub if needed.

**Comment by alexmorley** [comment]
(for entirely selfish reasons) I'm hesitant to do this right now just because I can work faster atm using the tool I'm more familiar with (github) but I think it's important to keep this option open for the near future. Can you copy past this into another issue? It's definitely worth re-visiting soon.

**Comment by alexmorley** [comment]
Closing this as continuous deployment is working.
